import localFont from 'next/font/local'
import React from 'react'

import type { Metadata } from 'next'

import 'react-quill/dist/quill.snow.css'
import './globals.css'

import Header from '@/components/Header'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <div className="inner_container">
          <div className="content_container">{children}</div>
        </div>
      </body>
    </html>
  )
}

export default RootLayout
